### ISSUE TITLE
表单样式小技巧集合

### ISSUE THREAD

**Issue by Chen-jj** [o2team/H5Skills#20]
## select下拉框 文字居右

![qq20160823-0_2x](https://user-images.githubusercontent.com/11807297/27893608-47657838-6239-11e7-92cb-e7435c338e9a.png)

```css
select {
    direction: rtl;
    -webkit-direction: rtl;
}
```

## input placeholder改颜色

```sass
input::-webkit-input-placeholder {color: #AAAAAA;}
input:focus::-webkit-input-placeholder {color: #EEEEEE;}
```

## iOS input 组件默认样式去除

```sass
-webkit-appearance: none;
```
