### ISSUE TITLE
行内块元素如何无缝平铺

### ISSUE THREAD

**Issue by leeenx** [o2team/H5Skills#48]
## 非safari环境

利用行内块元素(inline-block)可以比较优雅地替代浮动做块平铺显示，也可以避免浮动带来的一些负面影响。如下：

```css
.container{
	width: 600px;
	height: 60px;
	margin: 0 auto;
	font-family: -apple-system;
}
span{
	display: inline-block;
	width: 60px;
	height: 60px;
	background: #333;
	color: #fff;
}
```

```html
<div class="container">
	<span>1</span>
	<span>2</span>
	<span>3</span>
	<span>4</span>
	<span>5</span>
	<span>6</span>
	<span>7</span>
	<span>8</span>
	<span>9</span>
	<span>10</span>
</div>
```
然而，效果并不是想像的那样：

{{:blog:2016:04:1.png?200|}}

因为字体大小不为0，造成空白节点仍然地占用一个 字符串的空间！去空格的方法有两种:

### 方法一 

让行内块元素之间紧挨着，不留空白可以解决这个问题，如下：

```html
<div class="container">
	<span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span><span>10</span>
</div>
```

上面的方案显然不优雅。

### 方法二

一般情况下把container的font-size设置为0就可以解决问题了。如下：

```css
.container{
	width: 600px;
	height: 60px;
	margin: 0 auto;
	font-size: 0;
	font-family: -apple-system;
}
span{
	display: inline-block;
	width: 60px;
	height: 60px;
	background: #333;
	color: #fff;
	font-size: 24px;
}
```
{{:blog:2016:04:2.png?200|}}

## safari环境

一直都是使用 font-size: 0; 来做行内块无缝平铺的。最近，T4哥（姓李名伟亮号王子谥威廉I），发现需要使用font-size: 0; 在PC safari或iphone手机中不能解决无缝平铺。如下:

{{:blog:2016:04:3.png?200|}}

原因是font-family使用了 `-apple-system`造成的。解决的方法有3个：

### 方法一

与非safari环境一样。

### 方法二

使用letter-spacing取负值（-4px）来对冲因为`-apple-system`字体带来的空隙。如下：

```css
.container{
	width: 600px;
	height: 60px;
	margin: 0 auto;
	font-size: 0;
	font-family: -apple-system;
	letter-spacing: -4px;
}
span{
	display: inline-block;
	width: 60px;
	height: 60px;
	background: #333;
	color: #fff;
	font-size: 24px;
	letter-spacing: 0;
}
```
从html结构上看，保持了优雅，但是css上觉得怪怪的，letter-spacing是默认继承属性，导致容器和行内块子元素都要声明一个letter-spacing。

{{:blog:2016:04:4.png?200|}}

### 方法三

方法二看似很巧妙地解决了在safari下的问题。不过，抱着怀疑的精神来验证这个方案的完美性，验证的标准很简单 -- -- 无缝。

将行内块的背景做成半透明如下:

```css
.container{
	width: 600px;
	height: 60px;
	margin: 0 auto;
	font-size: 0;
	font-family: -apple-system;
	letter-spacing: -4px;
}
span{
	display: inline-block;
	width: 60px;
	height: 60px;
	background: rgba(0,0,0,。3);
	color: #fff;
	font-size: 24px;
	letter-spacing: 0;
}
```

在PC的safari和ip6的safari的观察结果如下：

{{:blog:2016:04:5.png?200|}}

{{:blog:2016:04:6.jpg?200|}}

很不幸地。。。。letter-spacing并不能完美解决无缝平铺的问题，边缘出现叠加了！！！

可以取巧地在container把font-family的字体改成none，然后再在行内块元素把font-family重置为 -apple-system，如下：

```css
.container{
	width: 600px;
	height: 60px;
	margin: 0 auto;
	font-size: 0;
	font-family: Helvetica;
}
span{
	display: inline-block;
	width: 60px;
	height: 60px;
	background: rgba(0,0,0,。3);
	color: #fff;
	font-size: 24px;
	font-family: -apple-system;
}
```
{{:blog:2016:04:7.png?200|}}

效果上是可以完美解决，html结构上也可以保持优雅。不过css上看跟letter-spacing方案相近。

## 后记

本文记于：2016/04/06 17:10
**当前（2017/07/11）主流的safari已经不存在这个问题了。这个问题只存在于 ios8.x **
