### ISSUE TITLE
开启3D加速会让fixed失效

### ISSUE THREAD

**Issue by leeenx** [o2team/H5Skills#54]
在开发过程发现以下代码，fixed 会失效：
```html
<div class="box">
    <p></p>
</div>
```

```css
.box{width:200px; height:200px; border:1px solid #CCC; -webkit-transform:translateZ(0);}
.box p{position:fixed; left:10x; top:10px; width:50px; height:50px; background-color:#000;}
```

按照常规渲染逻辑，fixed是相对于浏览器窗口进行定位，但对父元素开启3D加速后，它的定位参考物变成了父元素。
