### ISSUE TITLE
H5 页面适配 iPhoneX

### ISSUE THREAD

**Issue by liqinuo** [o2team/H5Skills#71]
对于网页而言，顶部（刘海部位）的适配问题浏览器已经做了处理，所以我们只需要关注底部与小黑条的适配问题即可（即常见的吸底导航、返回顶部等各种相对底部 fixed 定位的元素）。

## 第一步：设置网页在可视窗口的布局方式
新增 viweport-fit 属性，使得页面内容完全覆盖整个窗口：
```html
<meta name="viewport" content="width=device-width, viewport-fit=cover">
```

## 第二步：页面主体内容限定在安全区域内
```css
body {
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
}
```

## 第三步：fixed 元素的适配

类型一：fixed 完全吸底元素（bottom = 0）
```css
{
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
}
```

类型二：fixed 非完全吸底元素（bottom ≠ 0），比如 “返回顶部”、“侧边广告” 等
```css
{
  margin-bottom: constant(safe-area-inset-bottom);
  margin-bottom: env(safe-area-inset-bottom);
}
```

更详细请看：https://aotu.io/notes/2017/11/27/iphonex/
